{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_empty_login_form", "rerun": "0"}, "1": {"status": "ERROR", "message": "Fixture \"open_url\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "test_name": "test_login_with_valid_credential", "rerun": "0"}, "2": {"status": "ERROR", "message": "Fixture \"open_url\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "test_name": "test_logout", "rerun": "0"}}, "suite_name": "tests/test_login.py"}}}, "date": "November 09, 2022", "start_time": 1667969023.330282, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "0", "skip": "0", "error": "2", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}